name: afiliado_vendas_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  
  get: 
  lottie:
  sizer:
  hexcolor:
  cupertino_icons: ^1.0.6
  flutter_keyboard_visibility:  
  flutter_svg:  
  intl:
  extended_masked_text:  
  delayed_widget:
  web_color_picker:
  image_picker_web:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:    
    - assets/                

  
